/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2023-03-12 14:56:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class viewListItem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    String listName = (String) request.getAttribute("listName");
    String itemName = request.getAttribute("itemName").toString();
    String itemListLink = request.getAttribute("itemListLink").toString();
    String itemText = (String) request.getAttribute("itemText");
    String itemFileName = (String) request.getAttribute("itemFileName");
    String itemFilePath = (String) request.getAttribute("itemFilePath");
    String itemURL = (String) request.getAttribute("itemURL");
    String[] listNames = (String[]) request.getAttribute("listNames");

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "meta.jsp", out, false);
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write("    <section class=\"bg-light\">\n");
      out.write("        <!-- Go back to item's list button -->\n");
      out.write("        <div class=\"row text-center justify-content-center mb-5\">\n");
      out.write("            <form action=\"viewList.html\" method=\"get\">\n");
      out.write("                <input type=\"hidden\" name=\"listName\" value=\"");
      out.print(listName);
      out.write("\">\n");
      out.write("                <button type=\"submit\" class=\"btn btn-light\">Go Back To List: ");
      out.print(listName);
      out.write("</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("        <!-- Table to display item's data -->\n");
      out.write("        <div class=\"row table-responsive\">\n");
      out.write("            <div class=\"col-sm-10 offset-1\">\n");
      out.write("                <table class=\"table table-light text-center\" id=\"itemTable\">\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <td style=\"min-width: 120px;\">Type</td>\n");
      out.write("                            <td style=\"min-width: 300px;\">Data</td>\n");
      out.write("                            <td style=\"min-width: 500px;\">Edit</td>\n");
      out.write("                            <td style=\"min-width: 120px;\">Remove Item</td>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("\n");
      out.write("                    <tbody>\n");
      out.write("                        <!-- Item Name -->\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Item Name</td>\n");
      out.write("                            <td>");
      out.print(itemName);
      out.write("</td>\n");
      out.write("                            <!-- Change Item Name -->\n");
      out.write("                            <td>\n");
      out.write("                                <div class=\"col-sm-10 offset-1\">\n");
      out.write("                                    <form action=\"changeItemName.html\" method=\"get\">\n");
      out.write("                                        <input type=\"hidden\" name=\"listName\" value=\"");
      out.print(listName);
      out.write("\">\n");
      out.write("                                        <div class=\"input-group\">\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" name =\"newItemName\" pattern=\"[a-zA-Z0-9]+\" placeholder=\"New Item Name\" required>\n");
      out.write("                                            <button type=\"submit\" class=\"input-group-text\" name=\"itemName\" value=\"");
      out.print(itemName);
      out.write("\">Submit</button>\n");
      out.write("                                        </div>\n");
      out.write("                                    </form>\n");
      out.write("                                </div>\n");
      out.write("                            </td>\n");
      out.write("                            <!-- Delete Item -->\n");
      out.write("                            <td>\n");
      out.write("                                <form action=\"deleteItem.html\" method=\"get\">\n");
      out.write("                                    <input type=\"hidden\" name=\"listName\" value=\"");
      out.print(listName);
      out.write("\">\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-danger\" name=\"itemToDelete\" value=\"");
      out.print(itemName);
      out.write("\">Delete</button>\n");
      out.write("                                </form>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <!-- Item Link -->\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Item Link</td>\n");
      out.write("                            <td><a href=\"viewList.html?listName=");
      out.print(itemListLink);
      out.write('"');
      out.write('>');
      out.print(itemListLink);
      out.write("</a></td>\n");
      out.write("                            <!-- Link Item to another List -->\n");
      out.write("                            <td>\n");
      out.write("                                <div class=\"col-sm-10 offset-1\">\n");
      out.write("                                    <form action=\"setItemLink.html\" method=\"post\">\n");
      out.write("                                        <input type=\"hidden\" name=\"listName\" value=\"");
      out.print(listName);
      out.write("\">\n");
      out.write("                                        <input type=\"hidden\" name=\"itemName\" value=\"");
      out.print(itemName);
      out.write("\">\n");
      out.write("                                        <div class=\"input-group\">\n");
      out.write("                                            <select name=\"itemLinkedList\" class=\"form-control\"  required>\n");
      out.write("                                                ");

                                                    for (String currentListName : listNames){
                                                        if (!currentListName.equals(listName)){
                                                
      out.write("\n");
      out.write("                                                <option value=\"");
      out.print(currentListName);
      out.write('"');
      out.write('>');
      out.print(currentListName);
      out.write("</option>\n");
      out.write("                                                ");

                                                        }
                                                    }
                                                
      out.write(">\n");
      out.write("                                            </select>\n");
      out.write("                                            <button type=\"submit\" class=\"input-group-text\" name=\"itemName\" value=\"");
      out.print(itemName);
      out.write("\">Submit</button>\n");
      out.write("                                        </div>\n");
      out.write("                                    </form>\n");
      out.write("                                </div>\n");
      out.write("                            </td>\n");
      out.write("                            <!-- Link item back to its own list -->\n");
      out.write("                            <td>\n");
      out.write("                                <form action=\"setItemLink.html\" method=\"post\">\n");
      out.write("                                    <input type=\"hidden\" name=\"listName\" value=\"");
      out.print(listName);
      out.write("\">\n");
      out.write("                                    <input type=\"hidden\" name=\"itemName\" value=\"");
      out.print(itemName);
      out.write("\">\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-danger\" name=\"itemLinkedList\" value=\"\">Reset</button>\n");
      out.write("                                </form>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <!-- Item Text -->\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Item Text</td>\n");
      out.write("                            <td>");
      out.print(itemText);
      out.write("</td>\n");
      out.write("                            <!-- Set Item Text -->\n");
      out.write("                            <td>\n");
      out.write("                                <div class=\"col-sm-10 offset-1\">\n");
      out.write("                                    <form action=\"setItemText.html\" method=\"post\">\n");
      out.write("                                        <input type=\"hidden\" name=\"listName\" value=\"");
      out.print(listName);
      out.write("\">\n");
      out.write("                                        <div class=\"input-group\">\n");
      out.write("                                            <textarea class=\"form-control\" name =\"itemText\" placeholder=\"Add text..\" maxlength=\"1000\" required></textarea>\n");
      out.write("                                            <button type=\"submit\" class=\"input-group-text\" name=\"itemName\" value=\"");
      out.print(itemName);
      out.write("\">Submit</button>\n");
      out.write("                                        </div>\n");
      out.write("                                        <small class=\"form-text d-flex\">1000 Characters maximum.</small>\n");
      out.write("                                    </form>\n");
      out.write("                                </div>\n");
      out.write("                            </td>\n");
      out.write("                            <!-- Clear Item Text -->\n");
      out.write("                            <td>\n");
      out.write("                                <form action=\"setItemText.html\" method=\"post\">\n");
      out.write("                                    <input type=\"hidden\" name=\"listName\" value=\"");
      out.print(listName);
      out.write("\">\n");
      out.write("                                    <input type=\"hidden\" name=\"itemName\" value=\"");
      out.print(itemName);
      out.write("\">\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-danger\" name=\"itemText\" value=\"\">Clear</button>\n");
      out.write("                                </form>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <!-- Item URL -->\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Item URL</td>\n");
      out.write("                            <td><a href=\"");
      out.print(itemURL);
      out.write("\" target=\"_blank\">");
      out.print(itemURL);
      out.write("</a></td>\n");
      out.write("                            <!-- Set Item URL -->\n");
      out.write("                            <td>\n");
      out.write("                                <div class=\"col-sm-10 offset-1\">\n");
      out.write("                                    <form action=\"setItemURL.html\" method=\"post\">\n");
      out.write("                                        <input type=\"hidden\" name=\"listName\" value=\"");
      out.print(listName);
      out.write("\">\n");
      out.write("                                        <div class=\"input-group\">\n");
      out.write("                                            <input type=\"url\" class=\"form-control\" name =\"itemURL\" placeholder=\"https://\" required>\n");
      out.write("                                            <button type=\"submit\" class=\"input-group-text\" name=\"itemName\" value=\"");
      out.print(itemName);
      out.write("\">Submit</button>\n");
      out.write("                                        </div>\n");
      out.write("                                    </form>\n");
      out.write("                                </div>\n");
      out.write("                            </td>\n");
      out.write("                            <!-- Clear Item URL -->\n");
      out.write("                            <td>\n");
      out.write("                                <form action=\"setItemURL.html\" method=\"post\">\n");
      out.write("                                    <input type=\"hidden\" name=\"listName\" value=\"");
      out.print(listName);
      out.write("\">\n");
      out.write("                                    <input type=\"hidden\" name=\"itemName\" value=\"");
      out.print(itemName);
      out.write("\">\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-danger\" name=\"itemURL\" value=\"\">Clear</button>\n");
      out.write("                                </form>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <!-- Item File -->\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Item File</td>\n");
      out.write("                            <td><a href=\"");
      out.print(itemFilePath);
      out.write("\" target=\"_blank\">");
      out.print(itemFileName);
      out.write("</a></td>\n");
      out.write("                            <!-- Set Item File -->\n");
      out.write("                            <td>\n");
      out.write("                                <div class=\"col-sm-10 offset-1\">\n");
      out.write("                                    <form action=\"setItemFile.html\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("                                        <div class=\"input-group\">\n");
      out.write("                                            <input type=\"hidden\" name=\"listName\" value=\"");
      out.print(listName);
      out.write("\">\n");
      out.write("                                            <input type=\"file\" class=\"form-control\" name=\"file\" required>\n");
      out.write("                                            <button type=\"submit\" class=\"input-group-text\" name=\"itemName\" value=\"");
      out.print(itemName);
      out.write("\">Submit</button>\n");
      out.write("                                        </div>\n");
      out.write("                                    </form>\n");
      out.write("                                </div>\n");
      out.write("                            </td>\n");
      out.write("                            <!-- Delete Item File -->\n");
      out.write("                            <td>\n");
      out.write("                                <form action=\"deleteItemFile.html\" method=\"get\" enctype=\"multipart/form-data\">\n");
      out.write("                                    <input type=\"hidden\" name=\"listName\" value=\"");
      out.print(listName);
      out.write("\">\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-danger\" name=\"itemName\" value=\"");
      out.print(itemName);
      out.write("\">Clear</button>\n");
      out.write("                                </form>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
